// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArNi6zzJoHfSeJb0nFdnMnrU415q6SDrY',
    appId: '1:635167043642:web:5ccd895039c9a0e5278503',
    messagingSenderId: '635167043642',
    projectId: 'testproject-e2ae0',
    authDomain: 'testproject-e2ae0.firebaseapp.com',
    storageBucket: 'testproject-e2ae0.appspot.com',
    measurementId: 'G-BX7GTEHYQ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2XQPKR-0_a1Asdz-I4u0r4nJs8mf85BE',
    appId: '1:635167043642:android:6185a49ed0e7e0e8278503',
    messagingSenderId: '635167043642',
    projectId: 'testproject-e2ae0',
    storageBucket: 'testproject-e2ae0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBD_DjelpSvtzRMoMote0Nj1yWWai4bOaE',
    appId: '1:635167043642:ios:822d6f784c80d5ba278503',
    messagingSenderId: '635167043642',
    projectId: 'testproject-e2ae0',
    storageBucket: 'testproject-e2ae0.appspot.com',
    iosClientId: '635167043642-t0tg840oksuofeci514c41dpv6b13ujo.apps.googleusercontent.com',
    iosBundleId: 'com.example.phoneAuthAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBD_DjelpSvtzRMoMote0Nj1yWWai4bOaE',
    appId: '1:635167043642:ios:811181445100a8c4278503',
    messagingSenderId: '635167043642',
    projectId: 'testproject-e2ae0',
    storageBucket: 'testproject-e2ae0.appspot.com',
    iosClientId: '635167043642-qvqd1bnaot5te56is18svqr1ff768jhb.apps.googleusercontent.com',
    iosBundleId: 'com.example.phoneAuthAssignment.RunnerTests',
  );
}
